<?php

namespace Database\Seeders;

use App\Enums\ComplexityLevel;
use App\Enums\DurabilityLevel;
use App\Enums\ProductApprovalStatus;
use App\Models\Product;
use App\Models\ProductType;
use App\Models\User;
use Illuminate\Database\Seeder;

class ProductCatalogSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::query()->where('email', 'admin@example.com')->first();

        $types = collect([
            [
                'name' => 'Keramiek',
                'description' => 'Handgevormde keramische objecten en servies.',
            ],
            [
                'name' => 'Hout',
                'description' => 'Producten van massief hout en bamboe.',
            ],
            [
                'name' => 'Textiel',
                'description' => 'Textielproducten zoals tassen, dekens en woonaccessoires.',
            ],
            [
                'name' => 'Metaal',
                'description' => 'Metalen woonobjecten en functionele producten.',
            ],
            [
                'name' => 'Illustratie',
                'description' => 'Prints, posters en grafische ontwerpen.',
            ],
        ])->mapWithKeys(function (array $attributes): array {
            $type = ProductType::query()->updateOrCreate(
                ['name' => $attributes['name']],
                ['description' => $attributes['description']],
            );

            return [$attributes['name'] => $type];
        });

        $makers = User::query()
            ->whereIn('username', ['maker1', 'maker2', 'maker3', 'maker4', 'maker5', 'maker6'])
            ->get()
            ->keyBy('username');

        $products = [
            [
                'maker_username' => 'maker1',
                'type_name' => 'Keramiek',
                'name' => 'Zandkleurige Vaas',
                'slug' => 'keramiek-vaas-zand',
                'description' => 'Handgedraaide keramieken vaas met matte glazuurlaag en zachte zandtint.',
                'material' => 'Keramiek',
                'production_time_days' => 7,
                'complexity' => ComplexityLevel::High,
                'durability' => DurabilityLevel::High,
                'unique_feature' => 'Dubbele glazuurafwerking met subtiel kleurverloop.',
                'price_credit' => 79.95,
                'approval_status' => ProductApprovalStatus::Approved,
                'approved_by_admin_id' => $admin?->id,
                'approved_at' => now()->subDays(20),
                'rejection_reason' => null,
                'has_external_link' => false,
                'needs_moderation' => false,
                'is_active' => true,
                'is_deleted' => false,
            ],
            [
                'maker_username' => 'maker2',
                'type_name' => 'Hout',
                'name' => 'Eiken Wandplank Straal',
                'slug' => 'eiken-wandplank-straal',
                'description' => 'Massieve wandplank van eikenhout met onzichtbare bevestiging voor een strak interieur.',
                'material' => 'Eikenhout',
                'production_time_days' => 5,
                'complexity' => ComplexityLevel::Medium,
                'durability' => DurabilityLevel::High,
                'unique_feature' => 'Met de hand afgeronde voorzijde voor een zachtere lijn.',
                'price_credit' => 64.50,
                'approval_status' => ProductApprovalStatus::Approved,
                'approved_by_admin_id' => $admin?->id,
                'approved_at' => now()->subDays(16),
                'rejection_reason' => null,
                'has_external_link' => false,
                'needs_moderation' => false,
                'is_active' => true,
                'is_deleted' => false,
            ],
            [
                'maker_username' => 'maker3',
                'type_name' => 'Textiel',
                'name' => 'Linnen Shopper Groen',
                'slug' => 'linnen-shopper-groen',
                'description' => 'Herbruikbare shopper van gewassen linnen met verstevigde hengsels en binnenvak.',
                'material' => 'Linnen',
                'production_time_days' => 3,
                'complexity' => ComplexityLevel::Low,
                'durability' => DurabilityLevel::Medium,
                'unique_feature' => 'Binnenvak met contrasterend stiksel voor kleine spullen.',
                'price_credit' => 39.95,
                'approval_status' => ProductApprovalStatus::Approved,
                'approved_by_admin_id' => $admin?->id,
                'approved_at' => now()->subDays(12),
                'rejection_reason' => null,
                'has_external_link' => false,
                'needs_moderation' => false,
                'is_active' => true,
                'is_deleted' => false,
            ],
            [
                'maker_username' => 'maker4',
                'type_name' => 'Metaal',
                'name' => 'Messing Tafellamp Ember',
                'slug' => 'messing-tafellamp-ember',
                'description' => 'Tafellamp van messing met warme amberkleurige kap en draaibare hals.',
                'material' => 'Messing',
                'production_time_days' => 12,
                'complexity' => ComplexityLevel::High,
                'durability' => DurabilityLevel::High,
                'unique_feature' => 'Draaibare hals voor gericht licht op bureau of dressoir.',
                'price_credit' => 129.00,
                'approval_status' => ProductApprovalStatus::Rejected,
                'approved_by_admin_id' => $admin?->id,
                'approved_at' => now()->subDays(4),
                'rejection_reason' => 'Productfoto toont onduidelijke bedrading en mist detail van de aansluiting.',
                'has_external_link' => false,
                'needs_moderation' => true,
                'is_active' => true,
                'is_deleted' => false,
            ],
            [
                'maker_username' => 'maker5',
                'type_name' => 'Textiel',
                'name' => 'Woldeken Noord',
                'slug' => 'woldeken-noord',
                'description' => 'Wollen plaid met brede boord en ingeweven kleurverloop voor bank of stoel.',
                'material' => 'Wol',
                'production_time_days' => 6,
                'complexity' => ComplexityLevel::Medium,
                'durability' => DurabilityLevel::High,
                'unique_feature' => 'Kleurverloop dat per batch licht verschilt.',
                'price_credit' => 92.00,
                'approval_status' => ProductApprovalStatus::Pending,
                'approved_by_admin_id' => null,
                'approved_at' => null,
                'rejection_reason' => null,
                'has_external_link' => false,
                'needs_moderation' => true,
                'is_active' => true,
                'is_deleted' => false,
            ],
            [
                'maker_username' => 'maker6',
                'type_name' => 'Illustratie',
                'name' => 'Poster Kustlijn Print',
                'slug' => 'poster-kustlijn-print',
                'description' => 'Giclee print van een minimalistische kustlijn op gerecycled papier met smalle rand.',
                'material' => 'Gerecycled papier',
                'production_time_days' => 2,
                'complexity' => ComplexityLevel::Low,
                'durability' => DurabilityLevel::Medium,
                'unique_feature' => 'Genummerde kleine oplage met zachte natuurtinten.',
                'price_credit' => 27.50,
                'approval_status' => ProductApprovalStatus::Approved,
                'approved_by_admin_id' => $admin?->id,
                'approved_at' => now()->subDays(10),
                'rejection_reason' => null,
                'has_external_link' => true,
                'needs_moderation' => false,
                'is_active' => true,
                'is_deleted' => false,
            ],
            [
                'maker_username' => 'maker4',
                'type_name' => 'Metaal',
                'name' => 'Stalen Plantstandaard Arc',
                'slug' => 'stalen-plantstandaard-arc',
                'description' => 'Gebogen plantstandaard van gepoedercoat staal voor binnengebruik en smalle hoeken.',
                'material' => 'Staal',
                'production_time_days' => 9,
                'complexity' => ComplexityLevel::Medium,
                'durability' => DurabilityLevel::High,
                'unique_feature' => 'Open boogvorm die luchtig oogt ondanks massief materiaal.',
                'price_credit' => 71.00,
                'approval_status' => ProductApprovalStatus::Approved,
                'approved_by_admin_id' => $admin?->id,
                'approved_at' => now()->subDays(8),
                'rejection_reason' => null,
                'has_external_link' => false,
                'needs_moderation' => false,
                'is_active' => true,
                'is_deleted' => false,
            ],
            [
                'maker_username' => 'maker1',
                'type_name' => 'Keramiek',
                'name' => 'Keramiek Espresso Set',
                'slug' => 'keramiek-espresso-set',
                'description' => 'Set van twee espressokopjes met handgespikkelde afwerking en klein dienblad.',
                'material' => 'Keramiek',
                'production_time_days' => 4,
                'complexity' => ComplexityLevel::Medium,
                'durability' => DurabilityLevel::Medium,
                'unique_feature' => 'Elk kopje heeft een licht afwijkend gespikkeld patroon.',
                'price_credit' => 54.00,
                'approval_status' => ProductApprovalStatus::Approved,
                'approved_by_admin_id' => $admin?->id,
                'approved_at' => now()->subDays(7),
                'rejection_reason' => null,
                'has_external_link' => false,
                'needs_moderation' => false,
                'is_active' => true,
                'is_deleted' => false,
            ],
            [
                'maker_username' => 'maker2',
                'type_name' => 'Keramiek',
                'name' => 'Archief Vaas Slate',
                'slug' => 'archief-vaas-slate',
                'description' => 'Ouder model vaas in leisteenkleur dat uit de actieve catalogus is gehaald.',
                'material' => 'Keramiek',
                'production_time_days' => 8,
                'complexity' => ComplexityLevel::Medium,
                'durability' => DurabilityLevel::High,
                'unique_feature' => 'Vroege productielijn met smallere opening en zwaardere voet.',
                'price_credit' => 58.00,
                'approval_status' => ProductApprovalStatus::Approved,
                'approved_by_admin_id' => $admin?->id,
                'approved_at' => now()->subDays(40),
                'rejection_reason' => null,
                'has_external_link' => false,
                'needs_moderation' => false,
                'is_active' => false,
                'is_deleted' => true,
            ],
            [
                'maker_username' => 'maker5',
                'type_name' => 'Hout',
                'name' => 'Bamboe Desk Organizer',
                'slug' => 'bamboe-desk-organizer',
                'description' => 'Compact bureau-organizer van bamboe met vakken voor pennen, notities en telefoon.',
                'material' => 'Bamboe',
                'production_time_days' => 4,
                'complexity' => ComplexityLevel::Low,
                'durability' => DurabilityLevel::Medium,
                'unique_feature' => 'Schuine telefoonstandaard geintegreerd in de achterzijde.',
                'price_credit' => 34.95,
                'approval_status' => ProductApprovalStatus::Pending,
                'approved_by_admin_id' => null,
                'approved_at' => null,
                'rejection_reason' => null,
                'has_external_link' => false,
                'needs_moderation' => true,
                'is_active' => true,
                'is_deleted' => false,
            ],
        ];

        foreach ($products as $attributes) {
            Product::query()->updateOrCreate(
                ['slug' => $attributes['slug']],
                [
                    'maker_id' => $makers[$attributes['maker_username']]->id,
                    'product_type_id' => $types[$attributes['type_name']]->id,
                    'name' => $attributes['name'],
                    'description' => $attributes['description'],
                    'material' => $attributes['material'],
                    'production_time_days' => $attributes['production_time_days'],
                    'complexity' => $attributes['complexity'],
                    'durability' => $attributes['durability'],
                    'unique_feature' => $attributes['unique_feature'],
                    'price_credit' => $attributes['price_credit'],
                    'approval_status' => $attributes['approval_status'],
                    'approved_by_admin_id' => $attributes['approved_by_admin_id'],
                    'approved_at' => $attributes['approved_at'],
                    'rejection_reason' => $attributes['rejection_reason'],
                    'has_external_link' => $attributes['has_external_link'],
                    'needs_moderation' => $attributes['needs_moderation'],
                    'is_active' => $attributes['is_active'],
                    'is_deleted' => $attributes['is_deleted'],
                    'average_rating' => 0,
                    'review_count' => 0,
                ],
            );
        }
    }
}
